# Generated by Django 3.1.3 on 2020-11-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_postid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postid',
            new_name='post',
        ),
    ]
