# Generated by Django 3.1.3 on 2020-11-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201114_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
